name: Run Docker Script

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t chr-jan-page-script .

      - name: Run Docker container
        run: docker run chr-jan-page-script

      - name: Push repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add .
          git commit -m "modified [skip ci]" || echo "No changes to commit"
          git push
